### PR TITLE
fix(storage): Always create a reference when getting data from storage (fixes #132).

### LINKED ISSUE #132: Potential dangling data reference in client.
### Bug

When client gets the `Data` from a job result, `Spider` does not register data reference, and once the job is cleaned up, the data is also eligible to be garbage collected, and the client will refer to a `Data` no longer exists.

### Spider version

0f88fc29d99d767e3db54d7b11f7ab6867d57e59

### Environment

Ubuntu 22.04

### Reproduction steps

Create a client that runs `create_data_test` task in `work-test.hpp`, wait for 10 seconds, and pass the result data into a `data_test` task.

### PR DESCRIPTION
**Pull request by sitaowang1998**
# Description

## Problem
Spider currently only tracks `Data` references when they are created by a task or client. However, if a job returns a `Data` object to a client, Spider does not register that the client is referencing this `Data`. As a result, when the job is removed from storage, the `Data` may be garbage collected, even though the client is still referencing , leading to potential errors.

## Solution
This PR introduces new storage functions that retrieve `Data` and register a reference to it within the same transaction. All existing calls to `get_data` have been replaced with these new functions to ensure proper tracking of Data references. The associated tests have also been updated to reflect and validate the new behavior.

Fixes #132.

# Checklist

* [x] The PR satisfies the [contribution guidelines][yscope-contrib-guidelines].
* [x] This is a breaking change and that has been indicated in the PR title, OR this isn't a
  breaking change.
* [x] Necessary docs have been updated, OR no docs need to be updated.

# Validation performed

* [x] GitHub workflows pass.
* [x] Unit tests pass in dev container.
* [x] Integration tests pass in dev container.

[yscope-contrib-guidelines]: https://docs.yscope.com/dev-guide/contrib-guides-overview.html

## Summary by CodeRabbit

- **New Features**
	- Enhanced data retrieval to distinguish between driver and task sources, allowing more precise data association and access.
- **Refactor**
	- Updated job and function handling to explicitly track and propagate the source and ID of jobs and tasks throughout the system.
	- Modularized data retrieval with locality and added explicit transaction handling.
	- Adjusted function invocation signatures and task execution to include explicit task ID propagation.
- **Tests**
	- Improved tests to validate correct handling of task IDs and job associations in function execution and task management.

### CODE REVIEW

File: src/spider/storage/DataStorage.hpp [hunk 1]
```diff
@@ -32,6 +32,36 @@ class DataStorage {
             = 0;
     virtual auto get_data(StorageConnection& conn, boost::uuids::uuid id, Data* data) -> StorageErr
             = 0;
+    /**
+     * Get data and register data reference from a driver in a single transaction.
```
Comment (davidlion) [inline src/spider/storage/DataStorage.hpp:36]:
```suggestion
     * Get a data object and register a reference for it from the given driver in a single
     * transaction.
```
Feel free to improve on this further.

File: src/spider/storage/DataStorage.hpp [hunk 2]
```diff
@@ -32,6 +32,36 @@ class DataStorage {
...
+     */
+    virtual auto get_data_driver(
+            StorageConnection& conn,
+            boost::uuids::uuid driver_id,
+            boost::uuids::uuid data_id,
+            Data* data
+    ) -> StorageErr
+            = 0;
+    /**
+     * Get data and register data reference from a task in a single transaction.
```
Comment (davidlion) [inline src/spider/storage/DataStorage.hpp:51]:
```suggestion
     * Get a data object and register a reference for it from the given task in a single
     * transaction.
```

File: src/spider/storage/DataStorage.hpp [hunk 3]
```diff
@@ -32,6 +32,36 @@ class DataStorage {
...
             = 0;
+    /**
+     * Get data and register data reference from a driver in a single transaction.
+     * @param conn
+     * @param driver_id
+     * @param data_id
+     * @param data output data
+     * @return StorageErr::Success if the transaction succeed. Error types otherwise.
+     */
+    virtual auto get_data_driver(
```
Comment (davidlion) [inline src/spider/storage/DataStorage.hpp:43]: Double check I didn't miss this change anywhere.
```suggestion
    virtual auto get_driver_data(
```

File: src/spider/storage/DataStorage.hpp [hunk 4]
```diff
@@ -32,6 +32,36 @@ class DataStorage {
...
+            = 0;
+    /**
+     * Get data and register data reference from a task in a single transaction.
+     * @param conn
+     * @param task_id
+     * @param data_id
+     * @param data output data
+     * @return StorageErr::Success if the transaction succeed. Error types otherwise.
+     */
+    virtual auto get_data_task(
```
Comment (davidlion) [inline src/spider/storage/DataStorage.hpp:58]: Double check I didn't miss this change anywhere.
```suggestion
    virtual auto get_task_data(
```

File: src/spider/worker/FunctionManager.hpp [hunk 5]
```diff
@@ -301,7 +306,7 @@ class FunctionInvoker {
                 if constexpr (cIsSpecializationV<T, spider::Data>) {
                     boost::uuids::uuid const data_id = arg.as<boost::uuids::uuid>();
                     std::unique_ptr<Data> data = std::make_unique<Data>();
-                    err = data_store->get_data(*conn, data_id, data.get());
+                    err = data_store->get_data_task(*conn, task_id, data_id, data.get());
```
Comment (davidlion) [inline src/spider/worker/FunctionManager.hpp:309]:
```suggestion
                    err = data_store->get_task_data(*conn, task_id, data_id, data.get());
```

File: src/spider/client/Job.hpp [hunk 6]
```diff
@@ -302,7 +329,21 @@ class Job {
                 if (!optional_data_id.has_value()) {
                     throw ConnectionException{fmt::format("Output data ID is missing")};
                 }
-                err = m_data_storage->get_data(conn, optional_data_id.value(), &data);
+                if (m_source == JobSource::Driver) {
+                    err = m_data_storage->get_data_driver(
```
Comment (davidlion) [inline src/spider/client/Job.hpp:333]:
```suggestion
                    err = m_data_storage->get_driver_data(
```

File: src/spider/storage/mysql/MySqlStorage.hpp [hunk 7]
```diff
@@ -148,6 +148,18 @@ class MySqlDataStorage : public DataStorage {
             -> StorageErr override;
     auto get_data(StorageConnection& conn, boost::uuids::uuid id, Data* data)
             -> StorageErr override;
+    auto get_data_driver(
```
Comment (davidlion) [inline src/spider/storage/mysql/MySqlStorage.hpp:151]:
```suggestion
    auto get_driver_data(
```

File: src/spider/storage/mysql/MySqlStorage.hpp [hunk 8]
```diff
@@ -148,6 +148,18 @@ class MySqlDataStorage : public DataStorage {
...
+            StorageConnection& conn,
+            boost::uuids::uuid driver_id,
+            boost::uuids::uuid data_id,
+            Data* data
+    ) -> StorageErr override;
+    auto get_data_task(
```
Comment (davidlion) [inline src/spider/storage/mysql/MySqlStorage.hpp:157]:
```suggestion
    auto get_task_data(
```

File: src/spider/storage/mysql/MySqlStorage.cpp [hunk 9]
```diff
@@ -2074,42 +2074,114 @@ auto MySqlDataStorage::add_task_data(
...
+    } catch (sql::SQLException& e) {
+        static_cast<MySqlConnection&>(conn)->rollback();
+        return StorageErr{StorageErrType::OtherErr, e.what()};
+    }
+    static_cast<MySqlConnection&>(conn)->commit();
+    return StorageErr{};
+}
 
-        std::unique_ptr<sql::PreparedStatement> locality_statement(
+auto MySqlDataStorage::get_data_task(
```
Comment (davidlion) [inline src/spider/storage/mysql/MySqlStorage.cpp:2163]:
```suggestion
auto MySqlDataStorage::get_task_data(
```

File: src/spider/storage/mysql/MySqlStorage.cpp [hunk 10]
```diff
@@ -2074,42 +2074,114 @@ auto MySqlDataStorage::add_task_data(
...
+        }
+    } catch (sql::SQLException& e) {
+        static_cast<MySqlConnection&>(conn)->rollback();
+        return StorageErr{StorageErrType::OtherErr, e.what()};
+    }
+    static_cast<MySqlConnection&>(conn)->commit();
+    return StorageErr{};
+}
+
+auto MySqlDataStorage::get_data_driver(
```
Comment (davidlion) [inline src/spider/storage/mysql/MySqlStorage.cpp:2133]:
```suggestion
auto MySqlDataStorage::get_driver_data(
```

**Review by davidlion — CHANGES_REQUESTED** [review]

**Comment by sitaowang1998** [comment]
@coderabbit. Please create an issue about cleaning up storage functions that are used only in testing. Please create another issue about moving the data fetching from `FunctionManager` into worker.
